apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neurocred

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: neurocred
  managed-by: kustomize

